### ISSUE TITLE
TypeError: Cannot read property 'reason' of null

### ISSUE THREAD

**Issue by cmmcleod** [azeemba/eslint-plugin-json#1]
The linter throws an error under the following circumstances"

Example `bad_file.json`:
```json
{
  "my_string": "hello world"
}
bad_text
```

Running `eslint --ext .json bad_file.json` results in the following error

```bash
./node_modules/eslint-plugin-json/lib/index.js:39
                    message: error.reason,

TypeError: Cannot read property 'reason' of null
    at ./node_modules/eslint-plugin-json/lib/index.js:39:35
    at Array.map (native)
    at Object.module.exports.processors..json.postprocess (./node_modules/eslint-plugin-json/lib/index.js:35:27)
    at processText (./node_modules/eslint/lib/cli-engine.js:226:30)
    at processFile (./node_modules/eslint/lib/cli-engine.js:270:18)
    at executeOnFile (./node_modules/eslint/lib/cli-engine.js:617:23)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (./node_modules/eslint/lib/cli-engine.js:640:56)
    at Object.cli.execute (./node_modules/eslint/lib/cli.js:162:95)
    at Object.<anonymous> (./node_modules/eslint/bin/eslint.js:60:20)
```

Looking at https://github.com/azeemba/eslint-plugin-json/blob/master/lib/index.js#L35 it seems that there are other arguments to the map callback function that could be useful:

```
{ '0': null,
  '1': 1,
  '2':
   [ { scope: '(main)',
       raw: 'Unrecoverable syntax error.',
       code: 'E041',
       reason: 'Unrecoverable syntax error. (75% scanned).',
       line: 3,
       character: 1 },
     null ] }
```

**Comment by azeemba** [comment]
Fixed by c056ce3
